version: 2

workflows:
  version: 2
  stuff:
    jobs:
      - info
      
jobs:
  info:
    resource_class: medium
    docker:
      - image: circleci/nodejs
    steps:
      - run: cat /sys/fs/cgroup/memory/memory.limit_in_bytes
      - run: sleep 300
