version: 2

workflows:
  version: 2
  stuff:
    jobs:
      - info
      
jobs:
  info:
    resource_class: massive
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: |
          cat /sys/fs/cgroup/memory/memory.limit_in_bytes
          cat /sys/fs/cgroup/cpu/cpu.shares
      - run: sleep 300
